### ISSUE TITLE
Problem when activating the addon: ModuleNotFoundError: No module named 'BlenderBoneMerger-3

### ISSUE THREAD

**Issue by tizeta** [Betti83771/BlenderBoneMerger#1]
Hi Betti, 
I got this series of errors when I activated the addon, right after installing it:
<pre>Modules Installed (BlenderBoneMerger-3.0.0) from '/home/tizi/apps/blendAddons/blender4/BlenderBoneMerger-3.0.0.zip' into '/home/tizi/.config/blender/4.0/scripts/addons'
Traceback (most recent call last):
  File "/home/tizi/apps/blender-4.0.0-linux-x64/4.0/scripts/modules/addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "/home/tizi/apps/blender-4.0.0-linux-x64/4.0/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'BlenderBoneMerger-3' </pre>
I managed to get rid of the error by renaming the folder "BlenderBoneMerger-3.0.0" to "BlenderBoneMerger-3", directly in the Blender Addons folder.

**Comment by Betti83771** [comment]
Hello,
I have no idea why your folder had the wrong name. How did you download the addon?  

Edit: If you downloaded it from the releases page, I actually have some idea.
You should download it from the page https://github.com/Betti83771/BlenderBoneMerger->code->download zip, not from the releases page.  
 That one is for the CG Cookie addon updater. Actually is it a good point to be made to the authors that this versioning method breaks the blender install feature for past versions if you want to install manually without using the updater. A good fix is to rename the folder manually.
